name: CD

on:
  push:
    branches:
      - production  

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/460674569272/locations/global/workloadIdentityPools/cloud-pool/providers/github-provider"
          service_account: "gha-cloudrun-deployer@msaas-470316.iam.gserviceaccount.com"

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: msaas-470316

      - name: Deploy to Cloud Run
        run: |
          IMAGE="europe-west1-docker.pkg.dev/msaas-470316/repo/backend:${{ github.sha }}"
          gcloud run deploy backend \
            --image=$IMAGE \
            --platform=managed \
            --region=europe-west1 \
            --allow-unauthenticated
