name: CI

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
        
      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm run test:ci

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          token_format: access_token
          workload_identity_provider: projects/87458775841/locations/global/workloadIdentityPools/my-pool/providers/github-provider
          service_account: ci-cd-sa@multi-tenant-saas-470216.iam.gserviceaccount.com

      - name: Configure Docker for Google Cloud
        run: gcloud auth configure-docker europe-west1-docker.pkg.dev --quiet

      - name: Build and Push Docker Image
        run: |
          IMAGE=europe-west1-docker.pkg.dev/multi-tenant-saas-470216/multi-Tenant-PMSaaS/backend:${{ github.sha }}
          docker build -t $IMAGE ./backend
          docker push $IMAGE
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV
