# The name of this workflow as it appears in the GitHub Actions tab
name: CI - Docker Build and Test

# This workflow is triggered on a push to the specified branches
on:
  push:
    branches:
      - develop
      - production
  pull_request:
    branches:
      - develop

jobs:
  build-and-test-docker-image:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Authenticate to Google Cloud
      - name: 'Authenticate to Google Cloud'
        id: 'auth'
        uses: google-github-actions/auth@v2
        with:
            credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Step 3: Configure Docker to use gcloud credential helper
      - name: 'Set up Cloud SDK'
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      # Step 4: Build and push the Docker image
      - name: Build and push Docker image
        id: image_build
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          # The key change is here: we use the fully qualified, region-specific registry name
          tags: europe-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/multi-tenant-pmsaas:${{ github.sha }}
